Repository karaoke-dev/osu-framework-font, pull requests merged in 2023-03, with the labels that each got.

#322 Upgrade package to the latest.
  osu.Framework.Font.Tests/Shaders/OutlineShaderTest.cs
  osu.Framework.Font.Tests/Visual/BackgroundGridTestScene.cs
  osu.Framework.Font.Tests/Visual/FrameworkTestScene.cs
  osu.Framework.Font.Tests/Visual/FrameworkTestSceneTestRunner.cs
  osu.Framework.Font.Tests/Visual/Sprites/TestSceneKaraokeSpriteText.cs
  osu.Framework.Font.Tests/Visual/Sprites/TestSceneKaraokeSpriteTextTransforms.cs
  osu.Framework.Font.Tests/Visual/Sprites/TestSceneKaraokeSpriteTextWithShader.cs
  osu.Framework.Font.Tests/Visual/Sprites/TestSceneLyricSpriteText.cs
  osu.Framework.Font.Tests/osu.Framework.Font.Tests.csproj
  osu.Framework.Font/Graphics/CustomizedShaderBufferedDrawNode.cs
  osu.Framework.Font/Graphics/Shaders/CustomizedShader.cs
  osu.Framework.Font/Graphics/Shaders/ICustomizedShader.cs
  osu.Framework.Font/Graphics/Shaders/OutlineShader.cs
  osu.Framework.Font/Graphics/Shaders/PixelShader.cs
  osu.Framework.Font/Graphics/Shaders/RainbowShader.cs
  osu.Framework.Font/Graphics/Shaders/RepeatMovingBackgroundShader.cs
  osu.Framework.Font/Graphics/Shaders/ShadowShader.cs
  osu.Framework.Font/Graphics/Shaders/StepShader.cs
  osu.Framework.Font/Resources/Shaders/sh_CustomizedShaderGlobalUniforms.h
  osu.Framework.Font/Resources/Shaders/sh_Outline.fs
  osu.Framework.Font/Resources/Shaders/sh_Pixel.fs
  osu.Framework.Font/Resources/Shaders/sh_Rainbow.fs
  osu.Framework.Font/Resources/Shaders/sh_RepeatMovingBackground.fs
  osu.Framework.Font/Resources/Shaders/sh_Shadow.fs
  osu.Framework.Font/osu.Framework.Font.csproj
Labels: package, size/XL, API changed

#320 dotnet 7 compatibility things
  osu.Framework.Font/Graphics/Containers/MaskingContainer.cs
  osu.Framework.Font/Graphics/CustomizedShaderBufferedDrawNode.cs
  osu.Framework.Font/Graphics/MultiShaderBufferedDrawNodeSharedData.cs
  osu.Framework.Font/Graphics/Shaders/IStepShader.cs
  osu.Framework.Font/Graphics/Shaders/RepeatMovingBackgroundShader.cs
  osu.Framework.Font/Graphics/Shaders/ShadowShader.cs
  osu.Framework.Font/Graphics/Sprites/KaraokeSpriteText.cs
  osu.Framework.Font/Graphics/Sprites/KaraokeSpriteText_DrawNode.cs
  osu.Framework.Font/Graphics/Sprites/PositionText.cs
  osu.Framework.Font/Graphics/Sprites/TextIndex.cs
  osu.Framework.Font/IO/Stores/ShaderResourceStore.cs
  osu.Framework.Font/osu.Framework.Font.csproj
Labels: size/M

#331 Fix multiple shader render issue.
  osu.Framework.Font.Tests/Visual/Shaders/TestSceneStepShader.cs
  osu.Framework.Font/Graphics/MultiShaderBufferedDrawNode.cs
  osu.Framework.Font/Graphics/MultiShaderBufferedDrawNodeSharedData.cs
Labels: size/L, shader

#334 Fix the shadow shader has different shadow direction if using different renderer.
  osu.Framework.Font/Graphics/Extensions/RendererExtension.cs
  osu.Framework.Font/Graphics/Shaders/ShadowShader.cs
Labels: bug, size/M, shader

#335 Update package to the latest.
  osu.Framework.Font/osu.Framework.Font.csproj
Labels: size/XS, package
